[package]
name = "async-mutex"
version = "0.1.0"
authors = ["Nathan Dobson <nadobson@mac.com>"]
edition = "2018"

[dependencies]
futures = { path = "futures-rs/futures", version = "0.3.13", features = ["executor", "thread-pool"] }
loom = { path = "loom", version = "0.4.0" }
pin-project = "1.0.5"
either = "1.6.1"
rand = "0.8.3"